name: Deploy to Yandex Cloud Function

on:
    push:
        branches: [ main ]   # при пуше в ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug OIDC Token
        run: |
            TOKEN=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL")
            echo "Полный токен: $TOKEN"
            echo "$TOKEN" | jq -r '.value' | cut -d'.' -f2 | base64 -d | jq '.aud'


      - name: Get IAM token via OIDC federation
        id: get-iam-token
        uses: docker://ghcr.io/yc-actions/yc-iam-token-fed:1.0.0
        with:
          yc-sa-id: ${{ secrets.YC_SERVICE_ACCOUNT_ID }} # ID сервисного аккаунта 
          yc-oidc-provider-id: ${{ secrets.YC_OIDC_PROVIDER_ID }} # ID федерации

      - name: Deploy function
        uses: yc-actions/yc-sls-function@v4
        with:
          yc-sa-id: ${{ secrets.YC_SERVICE_ACCOUNT_ID }}
          folder-id: ${{ secrets.YC_FOLDER_ID }}
          function-name: ${{ secrets.YC_FUNCTION_NAME }}
          runtime: 'python312'
          entrypoint: 'tb_webhook.webhook'                
          memory: '1024Mb'
          execution-timeout: '3s'
          service-account-id: ${{ secrets.YC_SERVICE_ACCOUNT_ID }}
          environment: |
            API_TOKEN=${{ secrets.API_TOKEN }}
          include: |
            .
            requirements.txt